#ifndef _SYSINFO_
#define _SYSINFO_

#include "header.h"

typedef enum WIN_VERSION_INFO
{
	WIN_VERSION_NONE,
	WIN_VERSION_2K,
	WIN_VERSION_XP,
	WIN_VERSION_2K3,
	WIN_VERSION_VISTA_2008,
	WIN_VERSION_WIN7_2008R2,
	WIN_VERSION_WIN8_2012,
	WIN_VERSION_WIN81_2012R2,
	WIN_VERSION_WIN10,
} WIN_VERSION_INFO;

WIN_VERSION_INFO sysinfo_os_version();

#endif //_SYSINFO_